server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: polenta-mcp-server

# PrestoDB Configuration
presto:
  url: ${PRESTO_URL}
  user: ${PRESTO_USER}
  password: ${PRESTO_PASSWORD}
  catalog: ${PRESTO_CATALOG}
  schema: ${PRESTO_SCHEMA}
  query-timeout: ${PRESTO_QUERY_TIMEOUT:3000}



# MCP Server Configuration
mcp:
  server:
    name: "Polenta Data Lake Server"
    version: "1.0.0"
    description: "MCP Server for accessing PrestoDB data lake with user-friendly queries"
  helpers:
    enabled: true  # Set to false in production to disable REST wrapper endpoints
  
# Logging Configuration
logging:
  level:
    com.santec.polenta: DEBUG
    io.prestodb: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
